### ISSUE TITLE
Speedup fix

### ISSUE THREAD

**Issue by justtoask** [Defaultplayer001/Deus-Ex-Universe-Community-Update-#15]
[this](https://steamcommunity.com/sharedfiles/filedetails/?id=2048525175) guide on steam has a fix on the spedup issue, maybe it can be included? Also is there a invite to the discord?

**Comment by Defaultplayer001** [comment]
This has actually been included for a while, iirc theoretically the replacement exe should also solve it - buuut it didn't seem to hurt to have it as an extra safety net so made a dual demo record / speedup fix engine.dll. 

I didn't actually properly include that in the file archive before, so fixed that. Credits seem in order however.

Hopefully you've found it elsewhere in the past year, but here's the discord link jic https://discord.com/invite/jCFJ3A6

P.S. Sorry for the stupid late reply!
