### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by rafaelf82** [Defaultplayer001/Deus-Ex-Universe-Community-Update-#2]
Can't find install instructions or release anywhere.

**Comment by Defaultplayer001** [comment]
So this is a really late reply, but both of these have always been in the ReadMe on the main page?

**Comment by rafaelf82** [comment]
> So this is a really late reply, but both of these have always been in the ReadMe on the main page?

This one?
https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/blob/master/README.md

**Comment by Defaultplayer001** [comment]
That's for my overly ambitious long term plans of CU's for the franchise as a whole. 

It's why it says "Pay no attention to the man behind the curtain.
Only the DX1 community update is ready for use!"
From there you can click the very first link, the only one that's been updated  recently at all. 

https://i.imgur.com/SwtoJiK.png

https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/tree/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android

TBH, not sure how you found the root one without lookin' for it? I only ever publicly link the DX1 CU directory.
