### ISSUE TITLE
What mod is responsible for resolution option?

### ISSUE THREAD

**Issue by michaeljhkim** [Defaultplayer001/Deus-Ex-Universe-Community-Update-#25]
So I noticed that one of the mods here allows the in-game menu to have a bunch of resolution options. I just wanted to know which mod did that, so I could just add that one only.

**Comment by Defaultplayer001** [comment]
RF IIRC, TBH tho if resolution modification is all you want I'd just do it manually from the ini. Seems easier to me, but whatever you want!
