### ISSUE TITLE
Suggest integrating Deus Ex: Transcended

### ISSUE THREAD

**Issue by 3371-Alpha** [Defaultplayer001/Deus-Ex-Universe-Community-Update-#3]
[Deus Ex: Transcended](https://www.moddb.com/mods/deus-ex-transcended) is yet another fan patching project which appears to have gained a lot of traction recently. Of course that mod is more vanilla centric, so it has no support for BioMod or Shifter unlike yours. Also, hate to be a bother, but do you think you could consider adding support for the [Deus Ex Enhanced](https://www.moddb.com/mods/deus-ex-enhanced)/[unifiedDeusEx](https://www.moddb.com/mods/unified-deus-ex) (enhanced hud), [Deus Ex: Gore Mod](https://www.moddb.com/mods/deus-ex-gore-mod) and [Deus Ex- Modern(ish) Combat](https://www.moddb.com/mods/deus-ex-modernish-combat) (gameplay tweaks) mods. I would also have suggested GMDX, but the mod's so huge I wouldn't know were to begin with integrating support for it.

**Comment by Defaultplayer001** [comment]
Already planned actually! 

Creator of that is a friend of mine <3 

Really love DXT! 

Wouldn't use it by default thought to be clear, I do have very minor nitpicks with some changes, imho it's more of a "French Vanilla" then a pure Vanilla bugfix mod. 


I'm not sure I'd even call them "nitpicks", just things that make me go "Hmm, that's not quite vanilla".

It's pretty much impossible to deny that it's better, but I just worry it's not the pure 100% vanilla fixes I want the CU to be. 

Also, I'm of the belief that non-intrusive bugs should be kept. (Stuff like grenade climbing.)

I just wanna fix actually harmful stuff, and not change / add / improve anything. 

I've had the same reconsiderations of a couple aspects of Confix as well. 

That being said, it *is* gonna replace Huren as the basis for a future planned eventually-probably-gonna-happen "+" mode for the CU. 

It's just so great. 

Also no bother at all! Really love hearing suggestions.

I'll def add those to the lists of optional mods to add! 

GMDX is waay too big though yeah lol, literally and conceptually.

**Comment by Defaultplayer001** [comment]
Done! 

Everyone including me seems to *adore* DXT, so it's actually the *default* option now! Can be disabled ofc.
