### ISSUE TITLE
Deus EX GoG Goty + Revision 1.6.30 - Spanish Translation fails

### ISSUE THREAD

**Issue by FlaubertNHR** [Defaultplayer001/Deus-Ex-Universe-Community-Update-#34]
Hi, 
  I Installed DeusEx Goty (GoG 1.112fm(revision_1.6.1.0)), and then "Revision_1.112fm(revision_1.6.3.0)", Finally I installed Community Update (DXCU.3.3.2024-4-14.036). Game works, and menus and message in screen are in spanish... but people communications/conversations are in english.
It seems that -at least- "DeusExConText.u" in System and in Languages/GotyE/System  IS NOT _the spanish texts file but the english one. The same happens with RevisionConversationsText.u in  Revision/System/.
I think I fixed it copying files in spanish -from ClanDlan traduction- instead of those, so now the game is ¿fully? in spanish.
I also deleted the <user</Tmp folder (cached files?)

**Comment by Defaultplayer001** [comment]
Sorry, the CU doesn't support any interoperability with Revision - translation would have to be updated for it.
