### ISSUE TITLE
Missing Steam Input profile

### ISSUE THREAD

**Issue by kineticRib** [Defaultplayer001/Deus-Ex-Universe-Community-Update-#38]
On the 3.0 changelog you mention having created a custom Steam Input profile, however it seems to be gone.

I'm pretty sure that, since then, Valve has pushed out an update that wiped most, if not all custom profiles, this included.

If anyone has the profile backed up, I would appreciate if you reuploaded it, thank you.

PS. This is my very first time writing a Github issue, so hopefully I'm not causing any trouble.

**Comment by Defaultplayer001** [comment]
It's still showing as up for me? But - another user reported this issue on Discord. Maybe I can stills see it as the creator. I'll look into into and see what I can do, maybe just try to upload a duplicate lol.

**Comment by Defaultplayer001** [comment]
Noticed they were showing up in search, but not community profile list.
Updated them, and they seem to be showing now! Lemme know if that's not the case for you.

**Comment by kineticRib** [comment]
Alright, they show up now, thank you :)
