### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by mrzapp** [Defaultplayer001/Deus-Ex-Universe-Community-Update-#4]
Great work on this project!

It says on [this page](https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/tree/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android) that Linux support has been added, which got me very excited!

How does it work? I don't see any Linux executables in the System folder. If we still have to run the game through Wine, then what does "Linux support" refer to?

**Comment by Defaultplayer001** [comment]
Eh, "support" is likely too strong of a word. 

Wrote that down years ago when I thought "Oh hey this'll be so simple to de develop more." 

Rather, it was just pointed out to me iirc that everything yeah, just simply works in Wine except for like X thing which I changed. Or something, tbh it was forever ago and i don't exactly recall. 

Either way, additional Linux support has fallen by the wayside in favor of refining focus on more basic stuff when I recognized I was overzealous about a few things, namely the "Gotta have 'em all", mentality. (Jesus, just look at the root directory,)

This are things I still absolutely want to eventually do, but well: https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/blob/master/%5B1.0%5D%20Deus%20Ex%20-%20Windows-Linux-macOS-Android/CommunityUpdateFileArchiveDXPC/Muses/todo.png

Anyways, TLDR: I agree, the "Linux" strings are misleading and should be changed to something "WIne (Linux)" or something less so. 

Open to any suggestions ofc, and thanks for pointing this out!
