### ISSUE TITLE
2.0 installer fails when editing component is ticked

### ISSUE THREAD

**Issue by kotenok2000** [Defaultplayer001/Deus-Ex-Universe-Community-Update-#5]

**Comment by Defaultplayer001** [comment]
Thanks so much for mentioning! Already know, as mentioned here: https://www.moddb.com/mods/deus-ex-community-update/downloads/deus-ex-community-update-2-0-installer-2021-6-4-531

Will be in the next update, should be by end of month! 

Sorry for the trouble, and this highlights a good point: I should open any known issues here myself if a user posts about them elsewhere, to save helpful users like you the effort and confusion. <3

Thanks again!
