### ISSUE TITLE
Mouse Acceleration :(

### ISSUE THREAD

**Issue by lightstylez** [Defaultplayer001/Deus-Ex-Universe-Community-Update-#7]
Hi. I'm having issues with Mouse Acceleration. I cannot find any way to disable it with default install options. I tried using the included Deux Exe instead but then the in game menu sensitivity is so much higher than the look sensitivity & makes it unplayable for me. I tried looking on the Launch website, didn't find anything to do with a config. Any help?

**Comment by Tyler799** [comment]
How did you solve this?
